language: generic
os: linux

sudo: required
dist: trusty
group: deprecated-2017Q4


install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - rm -rf public || exit 0

script:
  - hugo version
  - chmod +x deploy-ci.sh
  - ./deploy-ci.sh